import { HomeCategory, SubGroups } from '@green-world/utils/types';
import { AtSign, ContactRound, Hash, Leaf, Phone, User } from 'lucide-react';
import { ReactNode } from 'react';

export type GroupItemCreateProduct = {
  key: keyof SubGroups;
  labelKey: string;
  icon: ReactNode;
};

export const navigationItems = [
  {
    id: 1,
    slug: 'ad',
    title: 'Dodaj oglas',
    route: '/create-ad',
    loggedRoute: '/create-ad'
  },
  {
    id: 2,
    slug: 'user',
    title: User,
    route: '/login',
    loggedRoute: '/profile'
  }
];

export const userDetails = [
  {
    id: 1,
    property: 'id',
    icon: Hash
  },
  {
    id: 2,
    property: 'name',
    icon: User
  },
  {
    id: 3,
    property: 'username',
    icon: ContactRound
  },
  {
    id: 4,
    property: 'email',
    icon: AtSign
  },
  {
    id: 5,
    property: 'phone',
    icon: Phone
  }
];

export const legalType = [
  {
    id: 1,
    name: 'Cvecara',
    slug: 'cvecara'
  },
  {
    id: 2,
    name: 'Rasadnik',
    slug: 'rasadnik'
  },
  {
    id: 3,
    name: 'Poljoprivredna apoteka',
    slug: 'poljoprivrednaApoteka'
  }
];

export const homeCategories: HomeCategory[] = [
  {
    id: 1,
    image: '2d8b043f2160cea64af1731b42541f53',
    route: '/products/flower_assortment',
    text: 'Cvetni asortiman',
    slug: 'flower_assortment'
  },
  {
    id: 2,
    image: '3f17dfde9f431e487fd89a32ce89148b',
    route: '/products/succulents',
    text: 'Sukulenti',
    slug: 'succulents'
  },
  {
    id: 3,
    image: '1363d60131ccd907b947f3f4e4663898',
    route: '/products/potted_flowers',
    text: 'Saksijsko cveće',
    slug: 'potted_flowers'
  },
  {
    id: 4,
    image: '3c4c4bb8a860deb0304f436dfb8e437e',
    route: '/products/seedlings',
    text: 'Sadnice',
    slug: 'seedlings'
  },
  {
    id: 5,
    image: 'd540fa10d54a991a487198281b307112',
    route: '/products/fruits_and_vegetables',
    text: 'Voće i povrće',
    slug: 'fruits_and_vegetables'
  },
  {
    id: 6,
    image: '2c67875e1e49b645e1bc24b592d60275',
    route: '/products/herbal_pharmacy',
    text: 'Biljna apoteka',
    slug: 'herbal_pharmacy'
  },
  {
    id: 7,
    image: '1ac106f726cfecf080d4bdc633290a0e',
    route: '/products/garden_decoration',
    text: 'Baštenska dekoracija',
    slug: 'garden_decoration'
  },
  {
    id: 8,
    image: '62527a20f31d727fdce4f488ec838f29',
    route: '/products/everything_for_plants',
    text: 'Sve za biljke',
    slug: 'everything_for_plants'
  },
  {
    id: 9,
    image: '0ab546d6f0fcfc38487383b36f1b6572',
    route: '/products/equipment_and_tools',
    text: 'Oprema i alati',
    slug: 'equipment_and_tools'
  },
  {
    id: 10,
    image: '1bef048d8ebb9c02621e8c7b14f50d32',
    route: '/products/urban_gardening',
    text: 'Urbano baštovanstvo',
    slug: 'urban_gardening'
  },
  {
    id: 11,
    image: '64e3c7031dd6b96fe72cfb4a23613250',
    route: '/products/seeds_and_bulbs',
    text: 'Semena i lukovice',
    slug: 'seeds_and_bulbs'
  },
  {
    id: 12,
    image: '509ee6d472fc1703e7639e633b6c38b4',
    route: '/products/eco_and_organic',
    text: 'Eko i Organsko',
    slug: 'eco_and_organic'
  }
];

export const categories = [
  'flower_assortment',
  'succulents',
  'potted_flowers',
  'seedlings',
  'fruits_and_vegetables',
  'herbal_pharmacy',
  'garden_decoration',
  'everything_for_plants',
  'equipment_and_tools',
  'urban_gardening',
  'seeds_and_bulbs',
  'eco_and_organic'
];

export const subGroups: SubGroups = {
  flower_assortment: [
    { label: 'bouquets', sr_RS: 'Buketi' },
    { label: 'cut_flowers', sr_RS: 'Cveće za sečenje' },
    { label: 'floral_gifts', sr_RS: 'Cvetni pokloni' },
    { label: 'floral_arrangements', sr_RS: 'Cvetne aranžmane' },
    { label: 'preserved_flowers', sr_RS: 'Očuvano cveće' },
    { label: 'roses', sr_RS: 'Ruže' },
    { label: 'tulips', sr_RS: 'Tulipani' },
    { label: 'lilies', sr_RS: 'Ljiljani' },
    { label: 'orchids', sr_RS: 'Orhideje' },
    { label: 'daisies', sr_RS: 'Margarete' },
    { label: 'sunflowers', sr_RS: 'Suncokreti' },
    { label: 'carnations', sr_RS: 'Karanfili' },
    { label: 'peonies', sr_RS: 'Božuri' },
    { label: 'gerberas', sr_RS: 'Gerberi' },
    { label: 'hydrangeas', sr_RS: 'Hortenzije' },
    { label: 'anemones', sr_RS: 'Anemone' },
    { label: 'ranunculus', sr_RS: 'Ranunculus' },
    { label: 'chrysanthemums', sr_RS: 'Hrizanteme' },
    { label: 'delphiniums', sr_RS: 'Delphinijumi' },
    { label: 'snapdragons', sr_RS: 'Zmajeve usne' },
    { label: 'asters', sr_RS: 'Astre' },
    { label: 'zinnias', sr_RS: 'Cinije' },
    { label: 'cosmos', sr_RS: 'Kosmos' },
    { label: 'freesias', sr_RS: 'Frezije' },
    { label: 'lavender', sr_RS: 'Lavanda' },
    { label: 'lilacs', sr_RS: 'Jorgovani' },
    { label: 'iris', sr_RS: 'Peršun' },
    { label: 'calla_lilies', sr_RS: 'Kala ljiljani' },
    { label: 'stock', sr_RS: 'Stock' },
    { label: 'salvia', sr_RS: 'Salvija' },
    { label: 'pansies', sr_RS: 'Ljubičice' },
    { label: 'petunias', sr_RS: 'Petunije' },
    { label: 'corydalis', sr_RS: 'Koridal' },
    { label: 'bouvardia', sr_RS: 'Bouvardija' },
    { label: 'calendula', sr_RS: 'Neven' }
  ],
  succulents: [
    { label: 'indoor_succulents', sr_RS: 'Sobne sočne biljke' },
    { label: 'outdoor_succulents', sr_RS: 'Vanjske sočne biljke' },
    { label: 'cacti', sr_RS: 'Kaktusi' },
    { label: 'succulent_gifts', sr_RS: 'Pokloni sočnih biljaka' },
    { label: 'echeveria', sr_RS: 'Eševerija' },
    { label: 'haworthia', sr_RS: 'Havortija' },
    { label: 'aloe_vera', sr_RS: 'Aloe vera' },
    { label: 'jade_plant', sr_RS: 'Biljka žada' },
    { label: 'string_of_pearls', sr_RS: 'Niz bisera' },
    { label: 'burros_tail', sr_RS: 'Rep magarca' },
    { label: 'zebra_plant', sr_RS: 'Zebrasta biljka' },
    { label: 'panda_plant', sr_RS: 'Panda biljka' },
    { label: 'agave', sr_RS: 'Agava' },
    { label: 'sedum', sr_RS: 'Sedum' },
    { label: 'crassula', sr_RS: 'Krasula' },
    { label: 'kalanchoe', sr_RS: 'Kalanhoe' }
  ],
  potted_flowers: [
    { label: 'indoor_plants', sr_RS: 'Sobne biljke' },
    { label: 'outdoor_plants', sr_RS: 'Vanjske biljke' },
    { label: 'flowering_plants', sr_RS: 'Cvetne biljke' },
    { label: 'decorative_plants', sr_RS: 'Dekorativne biljke' },
    { label: 'peace_lily', sr_RS: 'Ljiljan mira' },
    { label: 'snake_plant', sr_RS: 'Zmijska biljka' },
    { label: 'spider_plant', sr_RS: 'Paučinska biljka' },
    { label: 'orchids', sr_RS: 'Orhideje' },
    { label: 'begonias', sr_RS: 'Begonije' },
    { label: 'fuchsias', sr_RS: 'Fuksije' },
    { label: 'african_violets', sr_RS: 'Afričke ljubičice' },
    { label: 'geraniums', sr_RS: 'Geranijumi' },
    { label: 'chrysanthemums', sr_RS: 'Hrizanteme' },
    { label: 'poinsettia', sr_RS: 'Božićna zvezda' },
    { label: 'anthurium', sr_RS: 'Anthurijum' },
    { label: 'calathea', sr_RS: 'Kalateja' },
    { label: 'ficus', sr_RS: 'Fikus' },
    { label: 'bromeliads', sr_RS: 'Bromelije' },
    { label: 'philodendron', sr_RS: 'Filodendron' },
    { label: 'string_of_hearts', sr_RS: 'Srce na koncu' },
    { label: 'jade_plant', sr_RS: 'Biljka jade' },
    { label: 'zz_plant', sr_RS: 'ZZ biljka' },
    { label: 'pothos', sr_RS: 'Pothos' },
    { label: 'dracaena', sr_RS: 'Dracena' },
    { label: 'areca_palm', sr_RS: 'Areka palma' },
    { label: 'rubber_plant', sr_RS: 'Gumena biljka' },
    { label: 'cast_iron_plant', sr_RS: 'Gvozdena biljka' },
    { label: 'money_plant', sr_RS: 'Biljka novca' },
    { label: 'maranta', sr_RS: 'Maranta' },
    { label: 'bamboo_plant', sr_RS: 'Bambus' },
    { label: 'coleus', sr_RS: 'Koleus' },
    { label: 'sansevieria', sr_RS: 'Sanseverija' },
    { label: 'hoya', sr_RS: 'Hoja' },
    { label: 'philodendron_birkin', sr_RS: 'Filodendron birkin' },
    { label: 'neoregalia', sr_RS: 'Neoregalia' }
  ],
  seedlings: [
    { label: 'flower_seedlings', sr_RS: 'Cvetne sadnice' },
    { label: 'vegetable_seedlings', sr_RS: 'Povrtne sadnice' },
    { label: 'fruit_seedlings', sr_RS: 'Voćne sadnice' },
    { label: 'herb_seedlings', sr_RS: 'Biljne sadnice' },
    { label: 'rose_seedlings', sr_RS: 'Sadnice ruža' },
    { label: 'lavender_seedlings', sr_RS: 'Sadnice lavande' },
    { label: 'sunflower_seedlings', sr_RS: 'Sadnice suncokreta' },
    { label: 'petunia_seedlings', sr_RS: 'Sadnice petunija' },
    { label: 'marigold_seedlings', sr_RS: 'Sadnice nevena' },
    { label: 'tomato_seedlings', sr_RS: 'Sadnice paradajza' },
    { label: 'pepper_seedlings', sr_RS: 'Sadnice paprike' },
    { label: 'cucumber_seedlings', sr_RS: 'Sadnice krastavaca' },
    { label: 'zucchini_seedlings', sr_RS: 'Sadnice tikvica' },
    { label: 'cabbage_seedlings', sr_RS: 'Sadnice kupusa' },
    { label: 'carrot_seedlings', sr_RS: 'Sadnice šargarepe' },
    { label: 'lettuce_seedlings', sr_RS: 'Sadnice salate' },
    { label: 'apple_seedlings', sr_RS: 'Sadnice jabuka' },
    { label: 'pear_seedlings', sr_RS: 'Sadnice krušaka' },
    { label: 'plum_seedlings', sr_RS: 'Sadnice šljiva' },
    { label: 'cherry_seedlings', sr_RS: 'Sadnice trešanja' },
    { label: 'peach_seedlings', sr_RS: 'Sadnice breskvi' },
    { label: 'quince_seedlings', sr_RS: 'Sadnice dunja' },
    { label: 'walnut_seedlings', sr_RS: 'Sadnice oraha' },
    { label: 'apricot_seedlings', sr_RS: 'Sadnice kajsija' },
    { label: 'basil_seedlings', sr_RS: 'Sadnice bosiljka' },
    { label: 'oregano_seedlings', sr_RS: 'Sadnice origana' },
    { label: 'thyme_seedlings', sr_RS: 'Sadnice majčine dušice' },
    { label: 'mint_seedlings', sr_RS: 'Sadnice mente' },
    { label: 'rosemary_seedlings', sr_RS: 'Sadnice ruzmarina' },
    { label: 'autohtona_sljiva_seedlings', sr_RS: 'Autohtone šljive' },
    { label: 'vranac_grape_seedlings', sr_RS: 'Sadnice grožđa vranac' },
    { label: 'dunja_seedlings', sr_RS: 'Sadnice dunje' },
    { label: 'lesnik_seedlings', sr_RS: 'Sadnice lešnika' },
    { label: 'malina_seedlings', sr_RS: 'Sadnice maline' },
    { label: 'kupina_seedlings', sr_RS: 'Sadnice kupine' },
    { label: 'šljiva_požegača_seedlings', sr_RS: 'Šljive požeške' },
    { label: 'prokupac_grape_seedlings', sr_RS: 'Sadnice grožđa prokupac' },
    { label: 'thuja_seedlings', sr_RS: 'Sadnice tuja' },
    { label: 'juniper_seedlings', sr_RS: 'Sadnice juna' },
    { label: 'cypress_seedlings', sr_RS: 'Sadnice cipresa' },
    { label: 'arborvitae_seedlings', sr_RS: 'Sadnice arborvitaea' },
    { label: 'pine_seedlings', sr_RS: 'Sadnice bora' },
    { label: 'spruce_seedlings', sr_RS: 'Sadnice smreke' },
    { label: 'fir_seedlings', sr_RS: 'Sadnice jele' }
  ],
  fruits_and_vegetables: [
    { label: 'fresh_fruits', sr_RS: 'Sveže voće' },
    { label: 'apples', sr_RS: 'Jabuke' },
    { label: 'pears', sr_RS: 'Kruške' },
    { label: 'plums', sr_RS: 'Šljive' },
    { label: 'cherries', sr_RS: 'Trešnje' },
    { label: 'peaches', sr_RS: 'Breskve' },
    { label: 'apricots', sr_RS: 'Kajsije' },
    { label: 'quince', sr_RS: 'Dunje' },
    { label: 'strawberries', sr_RS: 'Jagode' },
    { label: 'raspberries', sr_RS: 'Maline' },
    { label: 'blackberries', sr_RS: 'Kupine' },
    { label: 'blueberries', sr_RS: 'Borovnice' },
    { label: 'grapes', sr_RS: 'Grožđe' },
    { label: 'fresh_vegetables', sr_RS: 'Sveže povrće' },
    { label: 'tomatoes', sr_RS: 'Paradajz' },
    { label: 'peppers', sr_RS: 'Paprika' },
    { label: 'cucumbers', sr_RS: 'Krastavci' },
    { label: 'zucchini', sr_RS: 'Tikvice' },
    { label: 'cabbage', sr_RS: 'Kupus' },
    { label: 'carrots', sr_RS: 'Šargarepe' },
    { label: 'lettuce', sr_RS: 'Salata' },
    { label: 'onions', sr_RS: 'Luk' },
    { label: 'garlic', sr_RS: 'Beli luk' },
    { label: 'potatoes', sr_RS: 'Krompir' },
    { label: 'spinach', sr_RS: 'Spanać' },
    { label: 'eggplant', sr_RS: 'Patlidžan' },
    { label: 'organic_produce', sr_RS: 'Organski proizvodi' },
    { label: 'organic_apples', sr_RS: 'Organske jabuke' },
    { label: 'organic_tomatoes', sr_RS: 'Organski paradajzi' },
    { label: 'organic_peppers', sr_RS: 'Organska paprika' },
    { label: 'organic_cucumbers', sr_RS: 'Organski krastavci' },
    { label: 'organic_spinach', sr_RS: 'Organski spanać' },
    { label: 'organic_carrots', sr_RS: 'Organske šargarepe' },
    { label: 'seasonal_fruits', sr_RS: 'Sezonsko voće' },
    { label: 'šljiva_požegača', sr_RS: 'Šljive požeške' },
    { label: 'malina', sr_RS: 'Malina' },
    { label: 'kupina', sr_RS: 'Kupina' },
    { label: 'dunja', sr_RS: 'Dunja' },
    { label: 'prokupac_grapes', sr_RS: 'Grožđe prokupac' },
    { label: 'jagoda', sr_RS: 'Jagoda' },
    { label: 'šljiva_ranka', sr_RS: 'Šljive ranka' },
    { label: 'exotic_fruits', sr_RS: 'Egzotično voće' },
    { label: 'bananas', sr_RS: 'Banane' },
    { label: 'mangoes', sr_RS: 'Manga' },
    { label: 'kiwi', sr_RS: 'Kivi' },
    { label: 'pineapple', sr_RS: 'Ananas' },
    { label: 'papaya', sr_RS: 'Papaja' },
    { label: 'pomegranate', sr_RS: 'Nar' },
    { label: 'dragon_fruit', sr_RS: 'Zmajevo voće' },
    { label: 'lychee', sr_RS: 'Liči' },
    { label: 'flower_seedlings', sr_RS: 'Cvetne sadnice' },
    { label: 'sunflower_seedlings', sr_RS: 'Sadnice suncokreta' },
    { label: 'vegetable_seedlings', sr_RS: 'Povrtne sadnice' },
    { label: 'tomato_seedlings', sr_RS: 'Sadnice paradajza' },
    { label: 'pepper_seedlings', sr_RS: 'Sadnice paprike' },
    { label: 'cucumber_seedlings', sr_RS: 'Sadnice krastavaca' },
    { label: 'zucchini_seedlings', sr_RS: 'Sadnice tikvica' },
    { label: 'cabbage_seedlings', sr_RS: 'Sadnice kupusa' },
    { label: 'carrot_seedlings', sr_RS: 'Sadnice šargarepe' },
    { label: 'lettuce_seedlings', sr_RS: 'Sadnice salate' },
    { label: 'spinach_seedlings', sr_RS: 'Sadnice spanaća' },
    { label: 'eggplant_seedlings', sr_RS: 'Sadnice patlidžana' },
    { label: 'fruit_seedlings', sr_RS: 'Voćne sadnice' },
    { label: 'apple_seedlings', sr_RS: 'Sadnice jabuka' },
    { label: 'pear_seedlings', sr_RS: 'Sadnice krušaka' },
    { label: 'plum_seedlings', sr_RS: 'Sadnice šljiva' },
    { label: 'cherry_seedlings', sr_RS: 'Sadnice trešanja' },
    { label: 'peach_seedlings', sr_RS: 'Sadnice breskvi' },
    { label: 'quince_seedlings', sr_RS: 'Sadnice dunja' },
    { label: 'walnut_seedlings', sr_RS: 'Sadnice oraha' },
    { label: 'apricot_seedlings', sr_RS: 'Sadnice kajsija' },
    { label: 'grape_seedlings', sr_RS: 'Sadnice grožđa' },
    { label: 'herb_seedlings', sr_RS: 'Biljne sadnice' },
    { label: 'basil_seedlings', sr_RS: 'Sadnice bosiljka' },
    { label: 'oregano_seedlings', sr_RS: 'Sadnice origana' },
    { label: 'thyme_seedlings', sr_RS: 'Sadnice majčine dušice' },
    { label: 'mint_seedlings', sr_RS: 'Sadnice mente' },
    { label: 'rosemary_seedlings', sr_RS: 'Sadnice ruzmarina' },
    { label: 'autohtona_sljiva_seedlings', sr_RS: 'Autohtone šljive' },
    { label: 'vranac_grape_seedlings', sr_RS: 'Sadnice grožđa vranac' },
    { label: 'dunja_seedlings', sr_RS: 'Sadnice dunje' },
    { label: 'lesnik_seedlings', sr_RS: 'Sadnice lešnika' },
    { label: 'malina_seedlings', sr_RS: 'Sadnice maline' },
    { label: 'kupina_seedlings', sr_RS: 'Sadnice kupine' },
    { label: 'šljiva_požegača_seedlings', sr_RS: 'Šljive požeške' },
    { label: 'prokupac_grape_seedlings', sr_RS: 'Sadnice grožđa prokupac' }
  ],
  herbal_pharmacy: [
    { label: 'medicinal_herbs', sr_RS: 'Lekovito bilje' },
    { label: 'herbal_teas', sr_RS: 'Biljni čajevi' },
    { label: 'essential_oils', sr_RS: 'Eterična ulja' },
    { label: 'herbal_extracts', sr_RS: 'Biljni ekstrakti' },
    { label: 'plant_fertilizers', sr_RS: 'Đubriva za biljke' },
    { label: 'organic_fertilizers', sr_RS: 'Organska đubriva' },
    { label: 'compost', sr_RS: 'Kompost' },
    { label: 'liquid_plant_food', sr_RS: 'Tečna ishrana za biljke' },
    { label: 'soil_amendments', sr_RS: 'Poboljšivači tla' },
    { label: 'root_boosters', sr_RS: 'Pojačivači korena' },
    { label: 'growth_stimulants', sr_RS: 'Stimulansi rasta' },
    { label: 'natural_pesticides', sr_RS: 'Prirodni pesticidi' },
    { label: 'fungicides', sr_RS: 'Fungicidi' },
    { label: 'insect_repellents', sr_RS: 'Repelenti za insekte' },
    { label: 'plant_antibiotics', sr_RS: 'Biljni antibiotici' },
    { label: 'bio_protectants', sr_RS: 'Bio zaštitnici' },
    { label: 'plant_vitamins', sr_RS: 'Vitamini za biljke' },
    { label: 'mineral_supplements', sr_RS: 'Mineralni dodaci' },
    { label: 'herbal_tinctures', sr_RS: 'Biljne tinkture' },
    { label: 'herbal_balm', sr_RS: 'Biljna mast' },
    { label: 'herbal_syrups', sr_RS: 'Biljni sirupi' },
    { label: 'herbal_cough_remedies', sr_RS: 'Biljni lekovi za kašalj' },
    { label: 'digestive_aids', sr_RS: 'Probavni dodaci' }
  ],
  garden_decoration: [
    { label: 'garden_statues', sr_RS: 'Baštenske statue' },
    { label: 'outdoor_lighting', sr_RS: 'Spoljašnje osvetljenje' },
    { label: 'garden_furniture', sr_RS: 'Baštenski nameštaj' },
    { label: 'decorative_pots', sr_RS: 'Dekorativni saksije' },
    { label: 'water_features', sr_RS: 'Vodeni elementi' },
    { label: 'garden_gnomes', sr_RS: 'Baštenski patuljci' },
    { label: 'bird_baths', sr_RS: 'Kupke za ptice' },
    { label: 'birdhouses', sr_RS: 'Kućice za ptice' },
    { label: 'wind_chimes', sr_RS: 'Vetrotresi' },
    { label: 'garden_trellises', sr_RS: 'Baštenski rešetke' },
    { label: 'pergolas', sr_RS: 'Pergole' },
    { label: 'hanging_planters', sr_RS: 'Viseće saksije' },
    { label: 'garden_sculptures', sr_RS: 'Baštenske skulpture' },
    { label: 'garden_pathways', sr_RS: 'Baštenski staze' },
    { label: 'decorative_fencing', sr_RS: 'Dekorativni ograde' },
    { label: 'garden_benches', sr_RS: 'Baštenske klupe' },
    { label: 'garden_swing_seats', sr_RS: 'Ljuljaške za baštu' },
    { label: 'gazebos', sr_RS: 'Sjenice' },
    { label: 'fire_pits', sr_RS: 'Ognjišta' },
    { label: 'outdoor_rugs', sr_RS: 'Spoljašnji tepisi' },
    { label: 'stepping_stones', sr_RS: 'Staze od kamenčića' },
    { label: 'flower_beds_borders', sr_RS: 'Ivice cvetnih leja' },
    { label: 'outdoor_carpets', sr_RS: 'Spoljašnji tepisi' },
    { label: 'raised_beds', sr_RS: 'Podignuti gredici' },
    {
      label: 'vertical_garden_structures',
      sr_RS: 'Vertikalne baštenske konstrukcije'
    },
    { label: 'outdoor_cushions', sr_RS: 'Spoljašnje jastučiće' },
    { label: 'patio_umbrellas', sr_RS: 'Suncobrani za terasu' },
    { label: 'garden_pavilions', sr_RS: 'Baštenski paviljoni' },
    { label: 'plant_stands', sr_RS: 'Postolja za biljke' },
    { label: 'garden_mirrors', sr_RS: 'Baštenska ogledala' },
    { label: 'outdoor_screens', sr_RS: 'Spoljašnji ekrani' },
    { label: 'solar_lights', sr_RS: 'Solarno svetlo' },
    { label: 'garden_ornaments', sr_RS: 'Baštenski ornament' }
  ],
  everything_for_plants: [
    { label: 'fertilizers', sr_RS: 'Đubriva' },
    { label: 'soil', sr_RS: 'Zemlja i supstrat' },
    { label: 'plant_protection', sr_RS: 'Zaštita biljaka' },
    { label: 'watering_systems', sr_RS: 'Sistemi za zalivanje' },
    { label: 'plant_stakes', sr_RS: 'Kolčići za biljke' },
    { label: 'plant_labels', sr_RS: 'Oznake za biljke' },
    { label: 'plant_cages', sr_RS: 'Kavezi za biljke' },
    { label: 'grow_lights', sr_RS: 'Svetla za rast' },
    { label: 'humidity_trays', sr_RS: 'Posude za vlagu' },
    { label: 'self_watering_pots', sr_RS: 'Samonalivajuće saksije' },
    { label: 'plant_misters', sr_RS: 'Prskalice za biljke' },
    { label: 'watering_cans', sr_RS: 'Kante za zalivanje' },
    { label: 'pruning_shears', sr_RS: 'Makaze za obrezivanje' },
    { label: 'gardening_gloves', sr_RS: 'Baštenske rukavice' },
    { label: 'plant_trays', sr_RS: 'Posude za sadnice' },
    { label: 'mulch', sr_RS: 'Malč' },
    { label: 'peat_moss', sr_RS: 'Treset' },
    { label: 'perlite', sr_RS: 'Perlit' },
    { label: 'vermiculite', sr_RS: 'Vermikulit' },
    { label: 'rooting_hormones', sr_RS: 'Hormoni za korenjenje' },
    { label: 'pest_control_sprays', sr_RS: 'Sprejevi za zaštitu od štetočina' },
    { label: 'biodegradable_pots', sr_RS: 'Biorazgradive saksije' },
    { label: 'plant_covers', sr_RS: 'Pokrivači za biljke' },
    { label: 'compost_bins', sr_RS: 'Kante za kompost' },
    { label: 'greenhouses', sr_RS: 'Staklenici' },
    { label: 'grow_tents', sr_RS: 'Šatori za uzgoj' },
    { label: 'plant_heating_mats', sr_RS: 'Grejne podloge za biljke' },
    { label: 'plant_grafting_tools', sr_RS: 'Alati za kalemljenje' },
    { label: 'hydroponic_systems', sr_RS: 'Hidroponski sistemi' },
    {
      label: 'drip_irrigation_kits',
      sr_RS: 'Setovi za kap po kap navodnjavanje'
    },
    { label: 'plant_nutrient_solutions', sr_RS: 'Rastvori za ishranu biljaka' },
    { label: 'planters_with_reservoirs', sr_RS: 'Saksije sa rezervoarima' },
    { label: 'plant_trellis', sr_RS: 'Rešetke za biljke' },
    { label: 'plant_clips', sr_RS: 'Stezaljke za biljke' },
    { label: 'bonsai_tools', sr_RS: 'Alati za bonsai' },
    { label: 'plant_saucers', sr_RS: 'Tanjirići za saksije' },
    { label: 'plant_supports', sr_RS: 'Potpore za biljke' },
    { label: 'pH_meters', sr_RS: 'pH metri' },
    { label: 'soil_test_kits', sr_RS: 'Setovi za ispitivanje tla' },
    { label: 'compost_tea_brewers', sr_RS: 'Spravljači čaja od komposta' },
    { label: 'knee_pads', sr_RS: 'Štitnici za kolena' },
    { label: 'garden_hose', sr_RS: 'Crevo za zalivanje' },
    { label: 'hose_reel', sr_RS: 'Namotač creva' },
    { label: 'watering_wand', sr_RS: 'Nastavak za zalivanje' },
    { label: 'harvest_basket', sr_RS: 'Korpa za berbu' }
  ],
  equipment_and_tools: [
    { label: 'hand_trowel', sr_RS: 'Ručna lopatica' },
    { label: 'transplanting_spade', sr_RS: 'Lopatica za presađivanje' },
    { label: 'dibber', sr_RS: 'Direktač za sadnju' },
    { label: 'bulb_planter', sr_RS: 'Sadilica za lukovice' },
    { label: 'hand_cultivator', sr_RS: 'Ručni kultivator' },
    { label: 'hand_weeder', sr_RS: 'Ručni alat za korove' },
    { label: 'soil_knife', sr_RS: 'Nož za zemlju' },
    { label: 'fruit_picker', sr_RS: 'Berač voća' },
    { label: 'garden_scissors', sr_RS: 'Baštenske makaze' },
    { label: 'loppers', sr_RS: 'Makaze za grane' },
    { label: 'pruning_saw', sr_RS: 'Pila za grane' },
    { label: 'bow_saw', sr_RS: 'Lučna pila' },
    { label: 'wheelbarrow', sr_RS: 'Kolica' },
    { label: 'garden_spade', sr_RS: 'Ašov' },
    { label: 'garden_hoe', sr_RS: 'Motika' },
    { label: 'garden_fork', sr_RS: 'Baštenske vile' },
    { label: 'garden_shovel', sr_RS: 'Lopata' },
    { label: 'grass_rake', sr_RS: 'Grablje za travu' },
    { label: 'hay_rake', sr_RS: 'Grablje za seno' },
    { label: 'scythe', sr_RS: 'Kosa' },
    { label: 'sickle', sr_RS: 'Srp' },
    { label: 'pickaxe', sr_RS: 'Pijuk' },
    { label: 'chainsaw', sr_RS: 'Motorna testera' },
    { label: 'electric_chainsaw', sr_RS: 'Električna motorna testera' },
    { label: 'lawn_mower', sr_RS: 'Kosilica' },
    { label: 'ride_on_mower', sr_RS: 'Traktorska kosilica' },
    { label: 'robot_mower', sr_RS: 'Robot kosilica' },
    { label: 'string_trimmer', sr_RS: 'Trimer za travu' },
    { label: 'battery_trimmer', sr_RS: 'Akumulatorski trimer' },
    { label: 'brush_cutter', sr_RS: 'Kosa za šipražje' },
    { label: 'hedge_trimmer', sr_RS: 'Trimer za živu ogradu' },
    { label: 'leaf_blower', sr_RS: 'Duvač lišća' },
    { label: 'garden_tiller', sr_RS: 'Motofrezar' },
    { label: 'cultivator', sr_RS: 'Kultivator' },
    { label: 'rotary_tiller', sr_RS: 'Rotofrezar' },
    { label: 'pressure_washer', sr_RS: 'Mašina za pranje pod pritiskom' },
    { label: 'lawn_aerator', sr_RS: 'Aerator za travnjak' },
    { label: 'scarifier', sr_RS: 'Skarifikator' },
    { label: 'garden_shredder', sr_RS: 'Drobilica za granje' },
    { label: 'sprayer_pump', sr_RS: 'Motorna prskalica' },
    { label: 'backpack_sprayer', sr_RS: 'Leđna prskalica' },
    { label: 'hand_sprayer', sr_RS: 'Ručna prskalica' },
    { label: 'pole_saw', sr_RS: 'Pila na motki' },
    { label: 'stump_grinder', sr_RS: 'Freza za panjeve' },
    { label: 'flail_mower', sr_RS: 'Malčer' },
    { label: 'snow_blower', sr_RS: 'Freza za sneg' },
    { label: 'log_splitter', sr_RS: 'Cepač za drva' },
    { label: 'seeder', sr_RS: 'Sejačica' },
    { label: 'irrigation_pump', sr_RS: 'Pumpa za navodnjavanje' },
    { label: 'submersible_pump', sr_RS: 'Potapajuća pumpa' },
    { label: 'water_pump_engine', sr_RS: 'Motopumpa' },
    { label: 'generator', sr_RS: 'Generator' },
    { label: 'compressor', sr_RS: 'Kompresor' },
    { label: 'tractor', sr_RS: 'Traktor' },
    { label: 'mini_tractor', sr_RS: 'Mini traktor' },
    { label: 'walk_behind_tractor', sr_RS: 'Motokultivar' },
    { label: 'tractor_plow', sr_RS: 'Plug za traktor' },
    { label: 'tractor_disc_harrow', sr_RS: 'Tanjirača' },
    { label: 'tractor_rotavator', sr_RS: 'Frezalica za traktor' },
    { label: 'tractor_sprayer', sr_RS: 'Traktorska prskalica' },
    { label: 'tractor_loader', sr_RS: 'Traktorski utovarivač' },
    { label: 'soil_auger', sr_RS: 'Bušač tla' },
    { label: 'lawn_spreader', sr_RS: 'Rasipač đubriva' },
    { label: 'soil_probe', sr_RS: 'Sonda za uzorkovanje tla' },
    { label: 'wire_cutters', sr_RS: 'Kliješta za žicu' }
  ],
  urban_gardening: [
    { label: 'balcony_containers', sr_RS: 'Kontejneri za balkon' },
    { label: 'terrace_planters', sr_RS: 'Saksije za terasu' },
    { label: 'window_boxes', sr_RS: 'Kutije za prozore' },
    { label: 'hanging_baskets', sr_RS: 'Viseće korpe' },
    { label: 'vertical_garden_kits', sr_RS: 'Setovi za vertikalni vrt' },
    { label: 'wall_planters', sr_RS: 'Zidne saksije' },
    { label: 'balcony_herbs', sr_RS: 'Začinsko bilje za balkon' },
    { label: 'microgreens', sr_RS: 'Mikrozelenilo' },
    { label: 'sprouting_kits', sr_RS: 'Setovi za klijanje' },
    { label: 'indoor_herb_gardens', sr_RS: 'Unutrašnji biljni vrtovi' },
    { label: 'compact_vegetable_varieties', sr_RS: 'Kompaktne sorte povrća' },
    { label: 'dwarf_fruit_trees', sr_RS: 'Patuljasta voćna stabla' },
    { label: 'raised_bed_kits', sr_RS: 'Setovi za podignuti gredić' },
    { label: 'grow_bags', sr_RS: 'Vreće za uzgoj' },
    {
      label: 'self_watering_containers',
      sr_RS: 'Kontejneri za samo-zalivanje'
    },
    { label: 'aquaponics_kits', sr_RS: 'Akvaponski setovi' },
    { label: 'hydroponic_kits', sr_RS: 'Hidroponski setovi' },
    { label: 'led_grow_lights', sr_RS: 'LED svetla za rast' },
    { label: 'indoor_composters', sr_RS: 'Unutrašnji kompostatori' },
    { label: 'worm_farms', sr_RS: 'Vermikomposter' },
    { label: 'balcony_wind_protection', sr_RS: 'Zaštita balkona od vetra' },
    { label: 'balcony_privacy_screens', sr_RS: 'Zaštita privatnosti balkona' },
    { label: 'compact_tools_set', sr_RS: 'Set kompaktnih alata' },
    { label: 'urban_seed_kits', sr_RS: 'Setovi semena za urbani vrt' },
    { label: 'strawberry_planters', sr_RS: 'Saksije za jagode' },
    { label: 'tomato_cage_planter', sr_RS: 'Saksija sa kavezom za paradajz' },
    { label: 'balcony_trellis', sr_RS: 'Rešetke za balkon' },
    { label: 'compact_compost_bins', sr_RS: 'Kompaktne kante za kompost' },
    { label: 'urban_bee_hotels', sr_RS: 'Urbani hoteli za pčele' },
    { label: 'outdoor_herb_pots', sr_RS: 'Saksije za začine' },
    { label: 'terrace_mini_greenhouse', sr_RS: 'Mini staklenik za terasu' },
    { label: 'rooftop_garden_kits', sr_RS: 'Setovi za krovni vrt' }
  ],
  seeds_and_bulbs: [
    { label: 'flower_seeds', sr_RS: 'Semena cveća' },
    { label: 'vegetable_seeds', sr_RS: 'Semena povrća' },
    { label: 'herb_seeds', sr_RS: 'Semena začinskog bilja' },
    { label: 'grass_seeds', sr_RS: 'Semena trave' },
    { label: 'wildflower_seeds', sr_RS: 'Semena divljeg cveća' },
    { label: 'organic_seeds', sr_RS: 'Organsko seme' },
    { label: 'heirloom_seeds', sr_RS: 'Autohtone sorte semena' },
    { label: 'sunflower_seeds_sow', sr_RS: 'Semena suncokreta za setvu' },
    { label: 'marigold_seeds', sr_RS: 'Semena nevena' },
    { label: 'petunia_seeds', sr_RS: 'Semena petunija' },
    { label: 'lavender_seeds', sr_RS: 'Semena lavande' },
    { label: 'basil_seeds', sr_RS: 'Semena bosiljka' },
    { label: 'tomato_seeds', sr_RS: 'Semena paradajza' },
    { label: 'pepper_seeds', sr_RS: 'Semena paprike' },
    { label: 'cucumber_seeds', sr_RS: 'Semena krastavca' },
    { label: 'carrot_seeds', sr_RS: 'Semena šargarepe' },
    { label: 'lettuce_seeds', sr_RS: 'Semena salate' },
    { label: 'spinach_seeds', sr_RS: 'Semena spanaća' },
    { label: 'pea_seeds', sr_RS: 'Semena graška' },
    { label: 'bean_seeds', sr_RS: 'Semena pasulja' },
    { label: 'pumpkin_seeds', sr_RS: 'Semena bundeve' },
    { label: 'hot_pepper_seeds', sr_RS: 'Semena ljutih papričica' },
    { label: 'chili_jalapeno_seeds', sr_RS: 'Semena jalapeño papričice' },
    { label: 'chili_habanero_seeds', sr_RS: 'Semena habanero papričice' },
    { label: 'chili_cayenne_seeds', sr_RS: 'Semena cayenne papričice' },
    { label: 'chili_serrano_seeds', sr_RS: 'Semena serrano papričice' },
    { label: 'chili_birds_eye_seeds', sr_RS: "Semena bird's eye papričice" },
    {
      label: 'chili_carolina_reaper_seeds',
      sr_RS: 'Semena Carolina Reaper papričice'
    },
    {
      label: 'chili_ghost_pepper_seeds',
      sr_RS: 'Semena ghost pepper papričice'
    },
    {
      label: 'chili_scotch_bonnet_seeds',
      sr_RS: 'Semena scotch bonnet papričice'
    },
    { label: 'chili_thai_seeds', sr_RS: 'Semena thai papričice' },
    { label: 'chili_poblano_seeds', sr_RS: 'Semena poblano papričice' },
    { label: 'tulip_bulbs', sr_RS: 'Lukovice tulipana' },
    { label: 'daffodil_bulbs', sr_RS: 'Lukovice narcisa' },
    { label: 'hyacinth_bulbs', sr_RS: 'Lukovice zumbula' },
    { label: 'crocus_bulbs', sr_RS: 'Lukovice krokusa' },
    { label: 'gladiolus_bulbs', sr_RS: 'Lukovice gladiole' },
    { label: 'lily_bulbs', sr_RS: 'Lukovice ljiljana' },
    { label: 'dahlia_tubers', sr_RS: 'Krtole dahlije' },
    { label: 'allium_bulbs', sr_RS: 'Lukovice allium-a' },
    { label: 'amaryllis_bulbs', sr_RS: 'Lukovice amarilisa' },
    { label: 'anemone_bulbs', sr_RS: 'Lukovice anemone' },
    { label: 'iris_bulbs', sr_RS: 'Lukovice perunika' },
    { label: 'muscari_bulbs', sr_RS: 'Lukovice plavih grozdova' },
    { label: 'ranunculus_bulbs', sr_RS: 'Lukovice ranunkulusa' },
    { label: 'begonia_tubers', sr_RS: 'Krtole begonija' },
    { label: 'caladium_bulbs', sr_RS: 'Lukovice kaladijuma' }
  ],
  eco_and_organic: [
    { label: 'organic_fertilizers_eco', sr_RS: 'Organska đubriva' },
    { label: 'bio_compost', sr_RS: 'Bio kompost' },
    { label: 'organic_plant_protection', sr_RS: 'Organska zaštita biljaka' },
    { label: 'natural_pesticides_eco', sr_RS: 'Prirodni pesticidi' },
    { label: 'eco_pots', sr_RS: 'Ekološke saksije' },
    { label: 'biodegradable_pots_eco', sr_RS: 'Biorazgradive saksije' },
    { label: 'organic_soil', sr_RS: 'Organska zemlja' },
    { label: 'peat_free_compost', sr_RS: 'Kompost bez treseta' },
    { label: 'organic_mulch', sr_RS: 'Organski malč' },
    { label: 'worm_castings', sr_RS: 'Vermikompost' },
    { label: 'natural_fertilizers', sr_RS: 'Prirodna đubriva' },
    { label: 'seaweed_fertilizer', sr_RS: 'Đubrivo od morskih algi' },
    { label: 'fish_emulsion', sr_RS: 'Emulzija od ribe' },
    { label: 'neem_oil', sr_RS: 'Neem ulje' },
    { label: 'diatomaceous_earth', sr_RS: 'Dijatomejska zemlja' },
    { label: 'copper_fungicide', sr_RS: 'Bakrni fungicid' },
    { label: 'sulphur_spray', sr_RS: 'Sumporni sprej' },
    { label: 'insect_hotels', sr_RS: 'Hoteli za insekte' },
    { label: 'butterfly_attractors', sr_RS: 'Privlačilice za leptire' },
    { label: 'bee_friendly_plants', sr_RS: 'Biljke privlačne za pčele' },
    { label: 'rain_barrel', sr_RS: 'Kaca za kišnicu' },
    { label: 'solar_garden_lights', sr_RS: 'Solarno baštensko osvetljenje' },
    { label: 'recycled_planters', sr_RS: 'Reciklovane saksije' },
    { label: 'cotton_plant_ties', sr_RS: 'Platnene veze za biljke' },
    { label: 'moss_poles', sr_RS: 'Mahovinski stubovi' },
    { label: 'eco_plant_labels', sr_RS: 'Ekološke oznake za biljke' },
    { label: 'bamboo_stakes', sr_RS: 'Bambusovi štapovi' },
    { label: 'coir_pots', sr_RS: 'Saksije od kokosovih vlakana' },
    { label: 'green_roof_kits', sr_RS: 'Setovi za zeleni krov' },
    { label: 'living_wall_kits', sr_RS: 'Setovi za živu ogradu' },
    { label: 'organic_honey', sr_RS: 'Organski med' },
    { label: 'beeswax_products', sr_RS: 'Proizvodi od pčelinjeg voska' },
    { label: 'organic_seeds_collection', sr_RS: 'Kolekcija organskih semena' }
  ]
};

export const groupItemsCreateProduct: GroupItemCreateProduct[] = [
  {
    key: 'flower_assortment',
    labelKey: 'catalog.groups.flower_assortment',
    icon: <Leaf />
  },
  {
    key: 'succulents',
    labelKey: 'catalog.groups.succulents',
    icon: <Leaf />
  },
  {
    key: 'potted_flowers',
    labelKey: 'catalog.groups.potted_flowers',
    icon: <Leaf />
  },
  {
    key: 'seedlings',
    labelKey: 'catalog.groups.seedlings',
    icon: <Leaf />
  },
  {
    key: 'fruits_and_vegetables',
    labelKey: 'catalog.groups.fruits_and_vegetables',
    icon: <Leaf />
  },
  {
    key: 'herbal_pharmacy',
    labelKey: 'catalog.groups.herbal_pharmacy',
    icon: <Leaf />
  },
  {
    key: 'garden_decoration',
    labelKey: 'catalog.groups.garden_decoration',
    icon: <Leaf />
  },
  {
    key: 'everything_for_plants',
    labelKey: 'catalog.groups.everything_for_plants',
    icon: <Leaf />
  },
  {
    key: 'equipment_and_tools',
    labelKey: 'catalog.groups.equipment_and_tools',
    icon: <Leaf />
  },
  {
    key: 'urban_gardening',
    labelKey: 'catalog.groups.urban_gardening',
    icon: <Leaf />
  },
  {
    key: 'seeds_and_bulbs',
    labelKey: 'catalog.groups.seeds_and_bulbs',
    icon: <Leaf />
  },
  {
    key: 'eco_and_organic',
    labelKey: 'catalog.groups.eco_and_organic',
    icon: <Leaf />
  }
];
